-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('AI & Automation');
INSERT INTO product_category(category_name) VALUES ('Developer Survival Gear');
INSERT INTO product_category(category_name) VALUES ('Cybersecurity & Spy Tech');
INSERT INTO product_category(category_name) VALUES ('Future Tech & Lifestyle');

-- -----------------------------------------------------
-- Products
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1000', 'AI Code Reviewer Pro', 'An AI code reviewer that analyzes pull requests, suggests improvements, and learns your coding patterns for increasingly accurate feedback with every sprint.', 'images/products/ai-automation/ai-automation-1000.png', 1, 250, 149.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1001', 'Auto-Deploy Button', 'One tap to ship. This physical button connects to your CI/CD pipeline and triggers deployments with a single press. Includes rollback guard and status LEDs.', 'images/products/ai-automation/ai-automation-1001.png', 1, 180, 196.92, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1002', 'Bug Prediction Engine', 'Stop chasing bugs — predict them. Scans your codebase for high-risk patterns and flags likely defect zones before they ever reach production.', 'images/products/ai-automation/ai-automation-1002.png', 1, 95, 244.83, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1003', 'Smart Log Analyzer', 'Tired of reading logs line by line? This AI-driven analyzer surfaces anomalies, correlates events across services, and generates plain-language summaries.', 'images/products/ai-automation/ai-automation-1003.png', 1, 60, 292.75, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1004', 'AI Standup Generator', 'Auto-generates standup updates from your Git commits, Jira tickets, and Slack threads. Never scramble for what to say in the morning meeting again.', 'images/products/ai-automation/ai-automation-1004.png', 1, 40, 340.67, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1005', 'Requirements-to-Code Converter', 'Paste in your product requirements and watch scaffolding appear. Generates boilerplate code, data models, and API stubs from natural-language specs.', 'images/products/ai-automation/ai-automation-1005.png', 1, 250, 388.58, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1006', 'Voice-Controlled Dev Assistant', 'Code hands-free. Run terminal commands, navigate files, and trigger autocomplete using just your voice — no keyboard required.', 'images/products/ai-automation/ai-automation-1006.png', 1, 180, 436.50, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1007', 'Predictive Incident Manager', 'Know about outages before your users do. Monitors system health and predicts incidents using historical patterns and real-time signals.', 'images/products/ai-automation/ai-automation-1007.png', 1, 95, 484.42, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1008', 'Self-Healing Infrastructure Module', 'Your infrastructure, but smarter. Detects configuration drift, auto-patches anomalies, and restores service health without human intervention.', 'images/products/ai-automation/ai-automation-1008.png', 1, 60, 532.33, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1009', 'AI Test Case Generator', 'Never write a boring test again. Reads your code and generates comprehensive test suites with edge cases, boundary conditions, and mocking strategies.', 'images/products/ai-automation/ai-automation-1009.png', 1, 40, 580.25, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1010', 'Codebase Summarizer Engine', 'Onboard new developers in minutes. Scans your entire repo and generates architecture overviews, dependency maps, and module-level summaries on demand.', 'images/products/ai-automation/ai-automation-1010.png', 1, 250, 628.17, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1011', 'Natural Language Query Engine for DBs', 'Ask your database questions in plain English. Translates natural-language queries into optimized SQL and returns formatted, shareable results instantly.', 'images/products/ai-automation/ai-automation-1011.png', 1, 180, 676.08, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1012', 'Smart Refactoring Tool', 'Refactor with confidence. Identifies code smells, suggests improvements, and applies safe, consistent changes across your entire codebase in seconds.', 'images/products/ai-automation/ai-automation-1012.png', 1, 95, 724.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1013', 'AI Pair Programmer Console', 'Like pair programming, but your partner never needs a coffee break. Offers real-time code suggestions, architecture advice, and inline documentation.', 'images/products/ai-automation/ai-automation-1013.png', 1, 60, 771.92, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1014', 'Auto-Scaling Intelligence Unit', 'Scale on instinct, not guesswork. Uses predictive analytics to auto-scale services ahead of traffic spikes and scale down during off-peak hours.', 'images/products/ai-automation/ai-automation-1014.png', 1, 40, 819.83, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1015', 'AI Security Vulnerability Scanner', 'Scans your codebase for security vulnerabilities using AI-driven pattern recognition. Identifies OWASP Top 10 risks and suggests targeted, actionable fixes.', 'images/products/ai-automation/ai-automation-1015.png', 1, 250, 867.75, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1016', 'Intelligent API Gateway', 'Route, throttle, and secure your APIs with AI-driven traffic analysis. Adapts rate limits dynamically and detects abuse patterns in real time.', 'images/products/ai-automation/ai-automation-1016.png', 1, 180, 915.67, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1017', 'ML Pipeline Builder Kit', 'Build, train, and deploy machine learning pipelines without writing boilerplate. Includes pre-built connectors for popular data sources and model registries.', 'images/products/ai-automation/ai-automation-1017.png', 1, 95, 963.58, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1018', 'Feature Flag Optimization Engine', 'Go beyond simple toggles. Uses real-time analytics to recommend optimal rollout strategies and audience segments for maximum impact and minimum risk.', 'images/products/ai-automation/ai-automation-1018.png', 1, 60, 1011.50, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1019', 'AI Product Manager Assistant', 'Summarize user feedback, prioritize backlogs, and draft roadmaps with AI. Keep your product strategy data-driven and your stakeholders aligned.', 'images/products/ai-automation/ai-automation-1019.png', 1, 40, 1059.42, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1020', 'ChatOps Automation Hub', 'Automate DevOps workflows from Slack or Teams. Deploy, monitor, rollback, and triage — all through simple chat commands powered by AI.', 'images/products/ai-automation/ai-automation-1020.png', 1, 250, 1107.33, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1021', 'Continuous Optimization Engine', 'Monitors app performance around the clock and suggests optimizations for speed, cost, and resource utilization across your cloud environments.', 'images/products/ai-automation/ai-automation-1021.png', 1, 180, 1155.25, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1022', 'Autonomous Data Cleanup Bot', 'Detects and resolves data quality issues like duplicates, missing values, and format inconsistencies — automatically and across all your databases.', 'images/products/ai-automation/ai-automation-1022.png', 1, 95, 1203.17, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1023', 'AI Cost Optimization Advisor', 'Analyze your cloud spending and get actionable recommendations to cut costs without sacrificing performance. Supports AWS, Azure, and GCP.', 'images/products/ai-automation/ai-automation-1023.png', 1, 60, 1251.08, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('AIA-1024', 'Multi-Agent Workflow Orchestrator', 'Coordinate multiple AI agents to handle complex, multi-step workflows. Define goals in natural language and let the orchestrator build the plan.', 'images/products/ai-automation/ai-automation-1024.png', 1, 40, 1299.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1000', 'Infinite Coffee Mug', 'The mug that never runs dry — at least in spirit. Features a heat-reactive fill gauge and a motivational quote that changes with every refill.', 'images/products/developer-gear/developer-gear-1000.png', 1, 250, 19.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1001', 'Works on My Machine Sticker Pack', '24 premium vinyl stickers featuring classic developer excuses. Waterproof, laptop-safe, and guaranteed to deflect blame in any code review.', 'images/products/developer-gear/developer-gear-1001.png', 1, 180, 28.58, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1002', 'Rubber Duck Debugging Assistant', 'The original debugging tool, upgraded. This premium rubber duck comes with a tiny lab coat and a monitor stand. Surprisingly effective.', 'images/products/developer-gear/developer-gear-1002.png', 1, 95, 38.17, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1003', 'Legacy Code Survival Kit', 'Everything you need to survive a legacy codebase: stress ball, aspirin, sticky notes, a flashlight, and a copy of the last known documentation.', 'images/products/developer-gear/developer-gear-1003.png', 1, 60, 47.75, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1004', 'Kubernetes Stress Ball', 'Squeeze away your orchestration anxiety. Shaped like the K8s helm wheel, this stress ball is perfect for cluster meltdowns and YAML nightmares.', 'images/products/developer-gear/developer-gear-1004.png', 1, 40, 57.33, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1005', 'PagerDuty Panic Button', 'A big red button for your desk that plays an alarm sound and flashes when pressed. Perfect for dramatizing production incidents or startling interns.', 'images/products/developer-gear/developer-gear-1005.png', 1, 250, 66.92, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1006', 'Dark Mode Everywhere Glasses', 'Tinted lenses that make the whole world look like dark mode. Reduces eye strain and makes fluorescent office lighting slightly more bearable.', 'images/products/developer-gear/developer-gear-1006.png', 1, 180, 76.50, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1007', 'Standup Blocker Headphones', 'Noise-canceling headphones with a built-in LED that reads In Flow State. Automatically mutes Slack notifications the moment you put them on.', 'images/products/developer-gear/developer-gear-1007.png', 1, 95, 86.08, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1008', 'Keyboard of Infinite Productivity', 'A mechanical keyboard with custom developer keycaps and a dedicated Deploy key. Cherry MX switches deliver that satisfying click with every commit.', 'images/products/developer-gear/developer-gear-1008.png', 1, 60, 95.67, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1009', 'Stack Overflow Offline Archive Drive', 'A portable SSD preloaded with the most popular Stack Overflow threads. For when your internet goes down but your deadlines do not.', 'images/products/developer-gear/developer-gear-1009.png', 1, 40, 105.25, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1010', 'Git Merge Conflict Resolver Wand', 'Wave this wand at your screen and feel the merge conflicts melt away. Does not actually resolve conflicts — emotional support only.', 'images/products/developer-gear/developer-gear-1010.png', 1, 250, 114.83, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1011', 'Instant Environment Replicator', 'A compact USB device that snapshots your local dev environment and recreates it anywhere. No more environment mismatch excuses.', 'images/products/developer-gear/developer-gear-1011.png', 1, 180, 124.42, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1012', 'Syntax Error Translator', 'A desk gadget that parses your compiler errors and translates them into plain English. Pairs with any IDE and supports 20+ languages.', 'images/products/developer-gear/developer-gear-1012.png', 1, 95, 134.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1013', 'Code Freeze Blanket', 'A cozy weighted blanket printed with frozen code snippets. Perfect for wrapping up during production freezes or post-deployment naps.', 'images/products/developer-gear/developer-gear-1013.png', 1, 60, 143.58, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1014', 'Weekend Protection Shield', 'A decorative desk shield that reads My weekend is not your sprint buffer. Place it prominently for maximum boundary-setting effectiveness.', 'images/products/developer-gear/developer-gear-1014.png', 1, 40, 153.17, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1015', 'Technical Debt Vacuum', 'A miniature desk vacuum shaped like a server rack. Cleans crumbs off your keyboard while reminding you of the tech debt you keep ignoring.', 'images/products/developer-gear/developer-gear-1015.png', 1, 250, 162.75, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1016', 'Infinite Undo Device', 'A retro gadget with a single button labeled Undo. Press it for reassuring clicks. Does not undo actual code, but you will feel better.', 'images/products/developer-gear/developer-gear-1016.png', 1, 180, 172.33, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1017', 'Burnout Prevention Smartwatch', 'Tracks your screen time, posture, and hydration. Sends gentle nudges to take breaks and stretch before burnout sneaks up on you.', 'images/products/developer-gear/developer-gear-1017.png', 1, 95, 181.92, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1018', 'Jira Ticket Auto-Completer', 'A smart notepad that drafts Jira ticket descriptions, acceptance criteria, and story points from rough notes. Say goodbye to backlog grooming.', 'images/products/developer-gear/developer-gear-1018.png', 1, 60, 191.50, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1019', 'Deployment Confidence Booster', 'A handheld device that plays a triumphant fanfare every time you deploy successfully. Includes a sad trombone mode for failed builds.', 'images/products/developer-gear/developer-gear-1019.png', 1, 40, 201.08, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1020', 'Debugging Time Machine', 'A novelty desk clock that counts backward, reminding you how much time debugging has claimed. Motivational or depressing — your call.', 'images/products/developer-gear/developer-gear-1020.png', 1, 250, 210.67, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1021', 'API Mock Generator Cube', 'Shake this desk cube and it generates realistic mock API responses. Great for front-end devs tired of waiting on backend teams.', 'images/products/developer-gear/developer-gear-1021.png', 1, 180, 220.25, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1022', 'CI Pipeline Speed Booster Chip', 'A decorative chip you place near your build server for good luck. Does it make CI faster? Probably not. But hope is a powerful thing.', 'images/products/developer-gear/developer-gear-1022.png', 1, 95, 229.83, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1023', 'Focus Mode Desk Light', 'An ambient LED desk light that syncs with your IDE. Turns green during productive flow states and red when your build is broken.', 'images/products/developer-gear/developer-gear-1023.png', 1, 60, 239.42, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('DSG-1024', 'Slack Auto-Responder Beacon', 'A desk beacon that auto-replies to Slack with In deep work mode when activated. Pairs with your calendar to block focus time automatically.', 'images/products/developer-gear/developer-gear-1024.png', 1, 40, 249.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1000', 'Self-Destructing USB Drive', 'Store sensitive files and set a timer. When it expires — or the wrong password is entered — the drive wipes itself clean, securely and permanently.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1000.png', 1, 250, 89.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1001', 'Encrypted Messaging Watch', 'A wrist-worn device that sends and receives end-to-end encrypted messages over a secure peer-to-peer channel. No cloud, no logs, no trace.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1001.png', 1, 180, 293.58, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1002', 'Voice Masking Tie Clip', 'Clip it on and alter your voice in real time during calls. Choose from multiple voice profiles — perfect for red team exercises and anonymous ops.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1002.png', 1, 95, 498.17, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1003', 'Portable Faraday Backpack', 'Block all wireless signals to your devices instantly. This RF-shielding backpack keeps phones, laptops, and trackers invisible to the network.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1003.png', 1, 60, 702.75, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1004', 'Biometric Spoofing Detector', 'Detects fake fingerprints, synthetic faces, and deepfake audio in real time. Protect your authentication systems from sophisticated spoofing attacks.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1004.png', 1, 40, 907.33, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1005', 'Zero-Trace VPN Router', 'A portable router that channels all connected traffic through an encrypted multi-hop VPN. Leaves no DNS or traffic logs. Travel-ready and field-tested.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1005.png', 1, 250, 1111.92, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1006', 'Ethical Password Audit Rig', 'A pre-configured hardware rig for testing password strength across your organization. Runs dictionary and brute-force audits ethically and with consent.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1006.png', 1, 180, 1316.50, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1007', 'Multi-Factor Authentication Keychain', 'A hardware security key supporting FIDO2, TOTP, and biometric verification. Compact, durable, and compatible with all major identity providers.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1007.png', 1, 95, 1521.08, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1008', 'Invisible Ink Smart Pen', 'Write notes invisible to the naked eye but readable with the included UV scanner app. Ideal for secure brainstorming and classified doodling.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1008.png', 1, 60, 1725.67, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1009', 'Network Intrusion Detection Appliance', 'A plug-and-play appliance that monitors your network for suspicious activity, unauthorized access, and data exfiltration attempts around the clock.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1009.png', 1, 40, 1930.25, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1010', 'Air-Gapped Laptop Kit', 'A fully configured laptop with no wireless hardware — no Wi-Fi, no Bluetooth, no cellular. The ultimate air-gapped workstation for sensitive work.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1010.png', 1, 250, 2134.83, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1011', 'Signal Interception Scanner', 'Scans for rogue cell towers, wireless skimmers, and unauthorized signal emitters in your vicinity. Alerts you to surveillance threats in real time.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1011.png', 1, 180, 2339.42, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1012', 'Deepfake Detection Glasses', 'AR-enabled glasses that analyze video feeds and flag deepfake content in real time. Highlights manipulation artifacts invisible to the naked eye.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1012.png', 1, 95, 2544.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1013', 'Secure File Drop Device', 'An encrypted dead-drop device for anonymous file sharing over short-range radio. No internet required. Files auto-delete after retrieval.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1013.png', 1, 60, 2748.58, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1014', 'Hardware Encryption Module', 'A tamper-resistant module that handles all encryption and key management in hardware. Meets FIPS 140-2 standards for enterprise-grade protection.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1014.png', 1, 40, 2953.17, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1015', 'GPS Spoofing Simulator', 'Test your fleet or app against GPS spoofing attacks. Generates fake GPS signals in a controlled RF environment for authorized security research.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1015.png', 1, 250, 3157.75, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1016', 'Anti-Phishing Filter AI', 'Analyzes emails, URLs, and messages in real time to detect phishing attempts. Learns your communication patterns to reduce false positives over time.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1016.png', 1, 180, 3362.33, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1017', 'Digital Identity Cloaking Service', 'Masks your digital footprint across the web. Rotates browser fingerprints, spoofs metadata, and blocks tracking pixels — all from a single device.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1017.png', 1, 95, 3566.92, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1018', 'Red Team Toolkit Case', 'A rugged carrying case pre-loaded with ethical hacking tools, network adapters, lock picks, and reference cards. Everything a pentester needs.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1018.png', 1, 60, 3771.50, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1019', 'Secure Boot Verification Chip', 'Verifies boot sequence integrity on every startup. Detects rootkits, bootkits, and firmware tampering before the OS even loads.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1019.png', 1, 40, 3976.08, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1020', 'Tamper-Proof Server Rack', 'A reinforced server rack with biometric locks, vibration sensors, and intrusion alerts. Stops physical attacks before they reach your hardware.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1020.png', 1, 250, 4180.67, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1021', 'AI Threat Intelligence Dashboard', 'Aggregates threat feeds from across the web and uses AI to prioritize risks specific to your organization. Visualize attack surfaces at a glance.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1021.png', 1, 180, 4385.25, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1022', 'Quantum-Resistant Encryption Module', 'Future-proof your data with post-quantum cryptographic algorithms designed to protect sensitive information against emerging quantum computing threats.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1022.png', 1, 95, 4589.83, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1023', 'Secure Chat Room Device', 'A self-contained encrypted device that hosts private chat rooms over a local mesh network. No internet, no metadata, no compromise.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1023.png', 1, 60, 4794.42, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('CST-1024', 'Data Exfiltration Prevention System', 'Monitors all outbound data channels and uses behavioral AI to detect and block unauthorized transfers before sensitive information leaves your network.', 'images/products/cybersecurity-spy-tech/cybersecurity-spy-tech-1024.png', 1, 40, 4999.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1000', 'Dream Recorder', 'Capture your dreams as audio journals the moment you wake. Uses EEG sensors and AI narration to turn subconscious adventures into shareable stories.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1000.png', 1, 250, 199.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1001', 'Memory Backup Drive', 'Back up your favorite memories as immersive 3D recordings. Relive birthdays, vacations, and milestones in full sensory detail whenever you want.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1001.png', 1, 180, 607.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1002', 'Focus Amplifier Headband', 'An EEG-powered headband that monitors brainwaves and plays adaptive sound frequencies to deepen concentration. Perfect for study sessions and deep work.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1002.png', 1, 95, 1015.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1003', 'Smart Mirror Honest Edition', 'A connected mirror that shows weather, calendar events, and health stats — plus brutally honest outfit feedback powered by a style-trained AI model.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1003.png', 1, 60, 1424.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1004', 'AI Life Planner', 'An AI assistant that syncs your goals, habits, and calendar to generate a personalized daily plan. Adapts in real time as priorities shift.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1004.png', 1, 40, 1832.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1005', 'Sleep Optimization Pod', 'A temperature-controlled pod with ambient sound, light therapy, and biometric tracking. Optimizes your sleep cycles for maximum rest in minimum time.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1005.png', 1, 250, 2240.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1006', 'Decision Fatigue Eliminator', 'Feed it your options — from dinner to career moves — and get AI-powered recommendations based on your values, goals, and past decisions.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1006.png', 1, 180, 2649.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1007', 'Time Perception Accelerator', 'A wearable that subtly adjusts ambient light and sound to make tedious tasks feel shorter. Warning: may cause meetings to seem almost bearable.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1007.png', 1, 95, 3057.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1008', 'Personal Drone Assistant', 'A compact, voice-controlled drone that follows you, carries small items, takes photos, and provides aerial navigation. Your personal flying sidekick.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1008.png', 1, 60, 3465.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1009', 'Smart Nutrition Scanner', 'Point it at any food and instantly get a breakdown of calories, macros, allergens, and ingredient quality. Syncs with your diet plan for live tracking.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1009.png', 1, 40, 3874.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1010', 'Emotion Regulation Wristband', 'Uses biometric sensors to detect stress, anxiety, and mood shifts. Delivers gentle haptic feedback and guided breathing exercises to help you recalibrate.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1010.png', 1, 250, 4282.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1011', 'Brain-Computer Interface Lite', 'Control simple apps, smart home devices, and media playback using only your thoughts. A consumer-friendly brain-computer interface for everyday use.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1011.png', 1, 180, 4690.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1012', 'AR Productivity Glasses', 'See your task list, calendar, and notifications overlaid on the real world. Voice-controlled and gesture-aware, with a sleek design for all-day wear.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1012.png', 1, 95, 5099.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1013', 'Home Automation Core AI', 'The brain of your smart home. Learns your routines and automates lighting, temperature, security, and appliances — adapting to your lifestyle over time.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1013.png', 1, 60, 5507.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1014', 'Personal Finance Optimization AI', 'Tracks spending, forecasts expenses, and suggests savings strategies tailored to your goals. Automates budgeting so you can focus on what matters.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1014.png', 1, 40, 5915.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1015', 'Biofeedback Training System', 'A full biofeedback rig with heart rate, skin conductance, and breathing sensors. Train your stress response through guided exercises and visualizations.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1015.png', 1, 250, 6324.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1016', 'Instant Language Translator Earbuds', 'Hear any language translated into yours in real time. Supports 50+ languages with sub-second latency — perfect for travel, business, and new friendships.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1016.png', 1, 180, 6732.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1017', 'Cognitive Load Balancer', 'Monitors your mental workload through eye tracking and EEG, then redistributes tasks across your devices to prevent cognitive overload.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1017.png', 1, 95, 7140.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1018', 'Digital Clone Assistant', 'Train a digital twin that handles your emails, schedules meetings, and responds just like you would. Free up hours every day for the work that matters.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1018.png', 1, 60, 7549.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1019', 'Virtual Workspace Projector', 'Project a full holographic workspace anywhere — desk, wall, or mid-air. Multiple virtual monitors, gesture controls, and spatial audio included.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1019.png', 1, 40, 7957.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1020', 'Health Risk Prediction Engine', 'Analyzes your biometrics, genetics, and lifestyle data to predict health risks years in advance. Get actionable recommendations to stay ahead of problems.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1020.png', 1, 250, 8365.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1021', 'Neural Learning Booster', 'Enhances memory retention and learning speed through targeted neurostimulation. Master new skills, languages, or certifications in record time.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1021.png', 1, 180, 8774.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1022', 'Personalized News Filter AI', 'Cuts through the noise and delivers only the news that matters to you. Filters out misinformation, bias, and clickbait using advanced language analysis.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1022.png', 1, 95, 9182.33, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1023', 'Life Analytics Dashboard Hub', 'Aggregates data from all your devices and apps into one dashboard. Tracks sleep, fitness, finances, productivity, and mood — all in one clear view.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1023.png', 1, 60, 9590.67, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id, date_created) VALUES ('FTL-1024', 'Habit Formation Engine', 'Uses behavioral science and AI nudges to help you build lasting habits. Tracks streaks, adjusts difficulty, and celebrates milestones along the way.', 'images/products/future-tech-lifestyle/future-tech-lifestyle-1024.png', 1, 40, 9999.00, 4, NOW());