# Automatically label PRs based on changed files

backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**/*'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

infrastructure:
  - changed-files:
    - any-glob-to-any-file:
      - 'terraform/**/*'
      - '.github/workflows/**/*'
      - 'docker-compose.yml'
      - 'Dockerfile'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/pom.xml'

security:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/security-scanning.yml'
      - '**/Dockerfile'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.spec.ts'
      - '**/*Test.java'
      - '**/*Tests.java'
