spring.datasource.url=jdbc:postgresql://localhost:5432/ats
spring.datasource.username=atsapp
spring.datasource.password=atsapp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
